// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.
// Body for: 2025-09-07/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2025-09-07/index.md"] = "![alt](articles/2025-09-07/cover.jpeg)\n\n- Dad: I love you, sweetheart.\n- 4yo Daughter: I love you too, Daddy.\n- Dad: I hope you don’t get tired of hearing me say that all the time.\n- 4yo Daughter: I'm never too tired of love.\n";
