// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.
// Body for: 2025-09-07/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2025-09-07/index.md"] = "-   **Dad**: I love you, sweetheart.\n-   **Daughter**: I love you too, Daddy.\n-   **Dad**: I hope you don’t get tired of hearing me say that all the time.\n-   **Daughter**: I'm never too tired of love.\n";
