#!/usr/bin/env node
/*
 * server.mjs — local-only admin server + build tool for the static blog.
 * Combines what used to live under scripts/ (manifest builder, article store,
 * and HTTP server) into one self-contained file. Never deploy this.
 *
 *   node server/server.mjs            start the admin server  →  http://127.0.0.1:8787/
 *   node server/server.mjs --build    regenerate articles/manifest.js + body bundles, then exit
 *
 * The in-page admin mode in index.html (⌘E / Ctrl+E) talks to this server's
 * /api/* endpoints. Requires no npm dependencies.
 */
import { createServer } from 'node:http';
import { readFile, writeFile, readdir, mkdir, rename, rm, stat } from 'node:fs/promises';
import { join, relative, sep, normalize, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

/* ======================================================================
 * Markdown / frontmatter helpers + manifest build
 * ==================================================================== */

export const stripFrontmatter = (t) =>
  t.replace(/^\uFEFF?---\s*\n[\s\S]*?\n---\s*\n?/, '').replace(/^\n+/, '');

export const isAbsUrl = (u) =>
  /^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#|data:|mailto:)/i.test(String(u).trim());

// Rewrite body-relative resource paths so they resolve from the site root.
export function rewriteRelativePaths(body, baseDir) {
  body = body.replace(/(!?\[[^\]]*\]\()([^)\s]+)/g, (m, pre, url) =>
    isAbsUrl(url) ? m : pre + baseDir + '/' + url.replace(/^\.\//, ''));
  body = body.replace(/\b(src|href)\s*=\s*("|')([^"']+)\2/gi, (m, attr, q, url) =>
    isAbsUrl(url) ? m : attr + '=' + q + baseDir + '/' + url.replace(/^\.\//, '') + q);
  return body;
}

export function parseFrontmatter(text) {
  const m = /^\uFEFF?---\s*\n([\s\S]*?)\n---\s*\n?/.exec(text);
  if (!m) return {};
  const data = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    let val = line.slice(i + 1).trim();
    if (val.startsWith('[') && val.endsWith(']')) {
      val = val.slice(1, -1)
        .split(',')
        .map((s) => s.trim().replace(/^["']|["']$/g, ''))
        .filter(Boolean);
    } else {
      val = val.replace(/^["']|["']$/g, '');
    }
    data[key] = val;
  }
  return data;
}

export const isTrue = (v) => v === true || v === 'true' || v === 'yes';

export async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) files.push(...(await walk(full)));
    else if (e.name === 'index.md') files.push(full);
  }
  return files;
}

// Regenerate manifest.js + each sibling index.js. Returns counts.
export async function regenerate({ articlesDir = 'articles', publicPrefix = 'articles' } = {}) {
  const files = await walk(articlesDir);
  const posts = [];
  let bodyCount = 0;

  for (const file of files) {
    const raw = await readFile(file, 'utf8');
    const fm = parseFrontmatter(raw);
    if (isTrue(fm.draft)) continue;

    const rel = relative(articlesDir, file).split(sep).join('/');
    const dirRel = rel.split('/').slice(0, -1).join('/');

    let date = fm.date || '';
    if (!date) {
      const m = /(\d{4})-(\d{2})-(\d{2})\//.exec(rel + '/');
      if (m) date = `${m[1]}-${m[2]}-${m[3]}`;
    }

    const tags = Array.isArray(fm.tags) ? fm.tags : fm.tags ? [fm.tags] : [];
    const title = fm.title || dirRel.split('/').pop();
    const slug = encodeURIComponent(date + '--' + title.replace(/ /g, '-'));

    let img = '';
    if (fm.img) {
      const v = String(fm.img).trim();
      img = isAbsUrl(v) ? v : ((dirRel ? dirRel + '/' : '') + v.replace(/^\.\//, ''));
    }

    posts.push({ slug, path: rel, title: fm.title || slug, date, tags, img });

    const baseDir = (publicPrefix + '/' + rel).split('/').slice(0, -1).join('/');
    const body = rewriteRelativePaths(stripFrontmatter(raw), baseDir);
    const bodyOut =
      '// Auto-generated by `node server/server.mjs --build` — do not edit by hand.\n' +
      '// Body for: ' + rel + '\n' +
      '(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})[' +
      JSON.stringify(rel) + '] = ' + JSON.stringify(body) + ';\n';
    await writeFile(join(articlesDir, rel.replace(/\.md$/, '.js')), bodyOut);
    bodyCount++;
  }

  posts.sort((a, b) => (b.date > a.date ? 1 : b.date < a.date ? -1 : 0));

  const out =
    '// Auto-generated by `node server.mjs --build` — do not edit by hand.\n' +
    'window.ARTICLES = ' + JSON.stringify(posts, null, 2) + ';\n';
  await writeFile(join(articlesDir, 'manifest.js'), out);
  return { posts: posts.length, bodies: bodyCount };
}

/* ======================================================================
 * Article store — filesystem CRUD on top of the helpers above
 * ==================================================================== */

// Build the frontmatter block (no trailing newline). Key order matches the
// existing articles: draft, title, tags, img (optional), date.
export function serializeFrontmatter({ draft, title, tags, img, date }) {
  const t = Array.isArray(tags) ? tags : [];
  const lines = ['---'];
  lines.push('draft: ' + (isTrue(draft) ? 'true' : 'false'));
  // Wrap the title in double quotes (matching the existing articles). This
  // round-trips losslessly through parseFrontmatter, which strips only the
  // outermost quote pair and never unescapes inner characters — so inner quotes
  // of either kind survive verbatim. (Titles are single-line, so no escaping is
  // needed beyond that.)
  lines.push('title: "' + String(title || '') + '"');
  lines.push('tags: [' + t.map((x) => JSON.stringify(String(x))).join(', ') + ']');
  if (img) lines.push("img: '" + String(img) + "'");
  lines.push('date: ' + String(date || ''));
  lines.push('---');
  return lines.join('\n');
}

export function buildMarkdown(fm, body) {
  const clean = String(body || '').replace(/^\s*\n+/, '').replace(/\s+$/, '');
  return serializeFrontmatter(fm) + '\n\n' + clean + '\n';
}

export function dirDate(dir) {
  const m = /^(\d{4}-\d{2}-\d{2})/.exec(String(dir || ''));
  return m ? m[1] : '';
}

// Pick the first free folder name for a date: base, then base-2, base-3, …
export function nextFreeDir(date, takenSet) {
  if (!takenSet.has(date)) return date;
  let n = 2;
  while (takenSet.has(date + '-' + n)) n++;
  return date + '-' + n;
}

// Folder names directly under articlesDir that contain an index.md.
export async function listDirNames(articlesDir) {
  let entries;
  try { entries = await readdir(articlesDir, { withFileTypes: true }); }
  catch { return []; }
  const names = [];
  for (const e of entries) {
    if (!e.isDirectory()) continue;
    try { await stat(join(articlesDir, e.name, 'index.md')); names.push(e.name); }
    catch { /* no index.md — skip */ }
  }
  return names;
}

function imgUrlFor(dir, img) {
  if (!img) return '';
  return isAbsUrl(img) ? img : 'articles/' + dir + '/' + String(img).replace(/^\.\//, '');
}

export async function listArticles(articlesDir) {
  const dirs = await listDirNames(articlesDir);
  const out = [];
  for (const dir of dirs) {
    const raw = await readFile(join(articlesDir, dir, 'index.md'), 'utf8');
    const fm = parseFrontmatter(raw);
    const tags = Array.isArray(fm.tags) ? fm.tags : fm.tags ? [fm.tags] : [];
    out.push({
      dir,
      title: fm.title || dir,
      date: fm.date || dirDate(dir),
      tags,
      draft: isTrue(fm.draft),
      img: fm.img || '',
      imgUrl: imgUrlFor(dir, fm.img || ''),
    });
  }
  out.sort((a, b) => (b.date > a.date ? 1 : b.date < a.date ? -1 : 0));
  return out;
}

export async function readArticle(articlesDir, dir) {
  const raw = await readFile(join(articlesDir, dir, 'index.md'), 'utf8');
  let assets = [];
  try {
    assets = (await readdir(join(articlesDir, dir, 'assets'), { withFileTypes: true }))
      .filter((e) => e.isFile()).map((e) => e.name);
  } catch { /* no assets dir */ }
  return { dir, raw, assets };
}

export async function allTags(articlesDir) {
  const set = new Set();
  for (const a of await listArticles(articlesDir)) a.tags.forEach((t) => set.add(t));
  return [...set].sort((a, b) => a.localeCompare(b));
}

// Create or update an article. Returns the final folder name.
export async function saveArticle(articlesDir, { originalDir, date, title, draft, tags, img, body }) {
  const md = buildMarkdown({ draft, title, tags, img, date }, body);
  const taken = new Set(await listDirNames(articlesDir));

  let targetDir;
  if (!originalDir) {
    targetDir = nextFreeDir(date, taken);
  } else if (dirDate(originalDir) === date) {
    targetDir = originalDir; // date unchanged → write in place
  } else {
    taken.delete(originalDir);
    targetDir = nextFreeDir(date, taken);
  }

  if (originalDir && targetDir !== originalDir) {
    await rename(join(articlesDir, originalDir), join(articlesDir, targetDir));
  }
  await mkdir(join(articlesDir, targetDir), { recursive: true });
  await writeFile(join(articlesDir, targetDir, 'index.md'), md, 'utf8');
  return targetDir;
}

export async function deleteArticle(articlesDir, dir) {
  await rm(join(articlesDir, dir), { recursive: true, force: true });
}

// Save an uploaded image into <dir>/assets/, returning its path relative to the
// article folder (e.g. "assets/diagram.png"). Names are sanitized and de-duped.
export async function saveUpload(articlesDir, dir, filename, buffer) {
  const assetsDir = join(articlesDir, dir, 'assets');
  await mkdir(assetsDir, { recursive: true });

  const safe = String(filename || 'image').replace(/[^\w.\-]+/g, '_').replace(/^\.+/, '') || 'image';
  const dot = safe.lastIndexOf('.');
  const base = dot > 0 ? safe.slice(0, dot) : safe;
  const ext = dot > 0 ? safe.slice(dot) : '';

  let name = base + ext;
  let n = 2;
  while (true) {
    try { await stat(join(assetsDir, name)); name = base + '-' + n++ + ext; }
    catch (e) { if (e.code !== 'ENOENT') throw e; break; } // free name found
  }
  await writeFile(join(assetsDir, name), buffer);
  return 'assets/' + name;
}

/* ======================================================================
 * HTTP server — static files + /api CRUD, with git commit/push per change
 * ==================================================================== */

const MIME = {
  '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8',
  '.md': 'text/markdown; charset=utf-8', '.svg': 'image/svg+xml',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.gif': 'image/gif', '.webp': 'image/webp', '.ico': 'image/x-icon',
};

// Allow the front-end (possibly served from another origin/domain) to call the
// admin API cross-origin. No cookies are used, so a wildcard origin is fine.
const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, DELETE, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Access-Control-Max-Age': '86400',
};

function sendJson(res, code, obj) {
  const body = JSON.stringify(obj);
  res.writeHead(code, { 'Content-Type': 'application/json; charset=utf-8', ...CORS });
  res.end(body);
}

function readBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', (c) => chunks.push(c));
    req.on('end', () => resolve(Buffer.concat(chunks)));
    req.on('error', reject);
  });
}

const execFileP = promisify(execFile);

// Stage everything, commit, and push — so each admin edit is persisted to git.
// Never throws: returns a status object the API echoes back. If root isn't a
// git repo (e.g. tests against a temp dir) it skips silently. A failed push
// (offline / no auth) still reports the successful local commit.
async function gitCommitPush(root, message) {
  try {
    await execFileP('git', ['rev-parse', '--is-inside-work-tree'], { cwd: root });
  } catch {
    return { skipped: true };
  }
  try {
    await execFileP('git', ['add', '-A'], { cwd: root });
    try {
      await execFileP('git', ['commit', '-m', message], { cwd: root });
    } catch (e) {
      const out = String((e.stdout || '') + (e.stderr || ''));
      if (/nothing to commit/i.test(out)) return { committed: false, pushed: false };
      throw e;
    }
    try {
      await execFileP('git', ['push'], { cwd: root });
      return { committed: true, pushed: true };
    } catch (e) {
      return { committed: true, pushed: false, error: String(e.stderr || e.message || e).trim() };
    }
  } catch (e) {
    return { committed: false, pushed: false, error: String(e.stderr || e.message || e).trim() };
  }
}

export function createAdminServer(root) {
  const articlesDir = join(root, 'articles');

  async function handleApi(req, res, url) {
    const p = url.pathname;
    try {
      if (p === '/api/articles' && req.method === 'GET') {
        return sendJson(res, 200, { articles: await listArticles(articlesDir) });
      }
      if (p === '/api/tags' && req.method === 'GET') {
        return sendJson(res, 200, { tags: await allTags(articlesDir) });
      }
      if (p === '/api/article' && req.method === 'GET') {
        const dir = url.searchParams.get('dir');
        if (!dir) return sendJson(res, 400, { error: 'dir required' });
        return sendJson(res, 200, await readArticle(articlesDir, dir));
      }
      if (p === '/api/article' && req.method === 'POST') {
        const data = JSON.parse((await readBody(req)).toString('utf8') || '{}');
        const dir = await saveArticle(articlesDir, data);
        await regenerate({ articlesDir });
        const git = await gitCommitPush(root, `admin: save "${data.title || dir}" (${dir})`);
        return sendJson(res, 200, { dir, git });
      }
      if (p === '/api/article' && req.method === 'DELETE') {
        const dir = url.searchParams.get('dir');
        if (!dir) return sendJson(res, 400, { error: 'dir required' });
        await deleteArticle(articlesDir, dir);
        await regenerate({ articlesDir });
        const git = await gitCommitPush(root, `admin: delete ${dir}`);
        return sendJson(res, 200, { ok: true, git });
      }
      if (p === '/api/upload' && req.method === 'POST') {
        const dir = url.searchParams.get('dir');
        const name = url.searchParams.get('name') || 'image';
        if (!dir) return sendJson(res, 400, { error: 'dir required' });
        const path = await saveUpload(articlesDir, dir, name, await readBody(req));
        return sendJson(res, 200, { path });
      }
      return sendJson(res, 404, { error: 'not found' });
    } catch (e) {
      return sendJson(res, 500, { error: String((e && e.message) || e) });
    }
  }

  async function handleStatic(req, res, url) {
    let rel = decodeURIComponent(url.pathname);
    if (rel === '/') rel = '/index.html';
    // Resolve safely within root; reject path traversal.
    const full = normalize(join(root, rel));
    if (full !== root && !full.startsWith(root + (process.platform === 'win32' ? '\\' : '/'))) {
      res.writeHead(403); return res.end('forbidden');
    }
    try {
      const info = await stat(full);
      if (info.isDirectory()) { res.writeHead(403); return res.end('forbidden'); }
      const buf = await readFile(full);
      res.writeHead(200, { 'Content-Type': MIME[extname(full).toLowerCase()] || 'application/octet-stream' });
      res.end(buf);
    } catch {
      res.writeHead(404); res.end('not found');
    }
  }

  return createServer((req, res) => {
    // new URL throws synchronously on a malformed request line — don't let that
    // crash the long-running dev server.
    let url;
    try { url = new URL(req.url ?? '/', 'http://127.0.0.1'); }
    catch { res.writeHead(400); res.end('bad request'); return; }
    const isApi = url.pathname.startsWith('/api/');
    // CORS preflight for cross-origin admin calls.
    if (isApi && req.method === 'OPTIONS') { res.writeHead(204, CORS); res.end(); return; }
    const done = isApi
      ? handleApi(req, res, url)
      : handleStatic(req, res, url);
    // Backstop: both handlers catch internally, but guard against any future
    // path that throws before its own try/catch.
    done.catch((e) => {
      if (!res.headersSent) sendJson(res, 500, { error: String((e && e.message) || e) });
      else res.end();
    });
  });
}

/* ======================================================================
 * CLI entry: `node server/server.mjs` serves; `node server/server.mjs --build` regenerates
 * ==================================================================== */

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--build')) {
    const { posts, bodies } = await regenerate();
    console.log(`Wrote ${posts} post(s) to articles/manifest.js`);
    console.log(`Wrote ${bodies} article body file(s) (sibling .js next to each .md)`);
  } else {
    const port = Number(process.env.PORT || 8787);
    const host = process.env.HOST || '127.0.0.1';
    const root = process.env.ADMIN_ROOT || process.cwd();
    createAdminServer(root).listen(port, host, () => {
      console.log(`Admin server: http://${host}:${port}/  (serving ${root})`);
      console.log('Press Ctrl+C to stop. Do not deploy this server.');
    });
  }
}
