// Auto-generated by `node server/server.mjs --build` — do not edit by hand.
// Body for: 2025-03-01/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2025-03-01/index.md"] = "Marriage is the character of love to bind with the person whom you truly love. And in this way you give yourself to the other – because that’s the best thing you have.\n";
