// Auto-generated by `node server/server.mjs --build` — do not edit by hand.
// Body for: 2024-12-28/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2024-12-28/index.md"] = "Go [here](http://thoughts.marcuschiu.com/2024/12/28/2024-reflection-the-year-of-openness/)\n";
