// scripts/lib/manifest.mjs
// Build logic for the static blog: scans an articles directory and writes
// manifest.js (the listing) + a sibling index.js body bundle per article.
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, relative, sep } from 'node:path';

export const stripFrontmatter = (t) =>
  t.replace(/^\uFEFF?---\s*\n[\s\S]*?\n---\s*\n?/, '').replace(/^\n+/, '');

export const isAbsUrl = (u) =>
  /^(?:[a-z][a-z0-9+.-]*:|\/\/|\/|#|data:|mailto:)/i.test(String(u).trim());

// Rewrite body-relative resource paths so they resolve from the site root.
export function rewriteRelativePaths(body, baseDir) {
  body = body.replace(/(!?\[[^\]]*\]\()([^)\s]+)/g, (m, pre, url) =>
    isAbsUrl(url) ? m : pre + baseDir + '/' + url.replace(/^\.\//, ''));
  body = body.replace(/\b(src|href)\s*=\s*("|')([^"']+)\2/gi, (m, attr, q, url) =>
    isAbsUrl(url) ? m : attr + '=' + q + baseDir + '/' + url.replace(/^\.\//, '') + q);
  return body;
}

export function parseFrontmatter(text) {
  const m = /^\uFEFF?---\s*\n([\s\S]*?)\n---\s*\n?/.exec(text);
  if (!m) return {};
  const data = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i === -1) continue;
    const key = line.slice(0, i).trim();
    let val = line.slice(i + 1).trim();
    if (val.startsWith('[') && val.endsWith(']')) {
      val = val.slice(1, -1)
        .split(',')
        .map((s) => s.trim().replace(/^["']|["']$/g, ''))
        .filter(Boolean);
    } else {
      val = val.replace(/^["']|["']$/g, '');
    }
    data[key] = val;
  }
  return data;
}

export const isTrue = (v) => v === true || v === 'true' || v === 'yes';

export async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const e of entries) {
    const full = join(dir, e.name);
    if (e.isDirectory()) files.push(...(await walk(full)));
    else if (e.name === 'index.md') files.push(full);
  }
  return files;
}

// Regenerate manifest.js + each sibling index.js. Returns counts.
export async function regenerate({ articlesDir = 'articles', publicPrefix = 'articles' } = {}) {
  const files = await walk(articlesDir);
  const posts = [];
  let bodyCount = 0;

  for (const file of files) {
    const raw = await readFile(file, 'utf8');
    const fm = parseFrontmatter(raw);
    if (isTrue(fm.draft)) continue;

    const rel = relative(articlesDir, file).split(sep).join('/');
    const dirRel = rel.split('/').slice(0, -1).join('/');

    let date = fm.date || '';
    if (!date) {
      const m = /(\d{4})-(\d{2})-(\d{2})\//.exec(rel + '/');
      if (m) date = `${m[1]}-${m[2]}-${m[3]}`;
    }

    const tags = Array.isArray(fm.tags) ? fm.tags : fm.tags ? [fm.tags] : [];
    const title = fm.title || dirRel.split('/').pop();
    const slug = encodeURIComponent(date + '--' + title.replace(/ /g, '-'));

    let img = '';
    if (fm.img) {
      const v = String(fm.img).trim();
      img = isAbsUrl(v) ? v : ((dirRel ? dirRel + '/' : '') + v.replace(/^\.\//, ''));
    }

    posts.push({ slug, path: rel, title: fm.title || slug, date, tags, img });

    const baseDir = (publicPrefix + '/' + rel).split('/').slice(0, -1).join('/');
    const body = rewriteRelativePaths(stripFrontmatter(raw), baseDir);
    const bodyOut =
      '// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.\n' +
      '// Body for: ' + rel + '\n' +
      '(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})[' +
      JSON.stringify(rel) + '] = ' + JSON.stringify(body) + ';\n';
    await writeFile(join(articlesDir, rel.replace(/\.md$/, '.js')), bodyOut);
    bodyCount++;
  }

  posts.sort((a, b) => (b.date > a.date ? 1 : b.date < a.date ? -1 : 0));

  const out =
    '// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.\n' +
    'window.ARTICLES = ' + JSON.stringify(posts, null, 2) + ';\n';
  await writeFile(join(articlesDir, 'manifest.js'), out);
  return { posts: posts.length, bodies: bodyCount };
}
