// Auto-generated by `node server/server.mjs --build` — do not edit by hand.
// Body for: 2026-02-03/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2026-02-03/index.md"] = "I find it easier to love her quietly than it is to genuinely believe that I am worthy of her love.\n";
