// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.
window.ARTICLES = [
  {
    "slug": "index",
    "path": "2026-02-03/index.md",
    "title": "Unworthy Love",
    "date": "2026-02-03",
    "tags": [],
    "img": "2026-02-03/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-09-07/index.md",
    "title": "4yo Wisdom",
    "date": "2025-09-07",
    "tags": [],
    "img": "2025-09-07/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-07-30/index.md",
    "title": "Christian Ramblings #2",
    "date": "2025-07-30",
    "tags": [],
    "img": "2025-07-30/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-07-09/index.md",
    "title": "Thoughts on Praise",
    "date": "2025-07-09",
    "tags": [],
    "img": "2025-07-09/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-07-06/index.md",
    "title": "A Fading Glimpse",
    "date": "2025-07-06",
    "tags": [],
    "img": "2025-07-06/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-04-23/index.md",
    "title": "Christian Ramblings #1",
    "date": "2025-04-23",
    "tags": [],
    "img": "2025-04-23/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-03-17/index.md",
    "title": "Conversation in the Womb – A Parable of Life After Delivery",
    "date": "2025-03-17",
    "tags": [],
    "img": "2025-03-17/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-03-01/index.md",
    "title": "Character of Love",
    "date": "2025-03-01",
    "tags": [],
    "img": "2025-03-01/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-01-27/index.md",
    "title": "Prune Your Time Like You Prune a Rose",
    "date": "2025-01-27",
    "tags": [],
    "img": "2025-01-27/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2025-01-15/index.md",
    "title": "Prayer Mantra #2",
    "date": "2025-01-15",
    "tags": [],
    "img": "2025-01-15/cover.jpeg"
  },
  {
    "slug": "index",
    "path": "2024-12-28/index.md",
    "title": "2024 Reflection – The Year of Openness",
    "date": "2024-12-28",
    "tags": [],
    "img": "2024-12-28/cover.png"
  }
];
