// Auto-generated by `node server.mjs --build` — do not edit by hand.
window.ARTICLES = [
  {
    "slug": "2026-06-23--What-is-Beauty%3F",
    "path": "2026-06-23/index.md",
    "title": "What is Beauty?",
    "date": "2026-06-23",
    "tags": [
      "beauty",
      "love",
      "aesthetics",
      "reflection",
      "relationships",
      "life",
      "philosophy"
    ],
    "img": "2026-06-23/assets/beauty.jpeg"
  },
  {
    "slug": "2026-02-03--Unworthy-Love",
    "path": "2026-02-03/index.md",
    "title": "Unworthy Love",
    "date": "2026-02-03",
    "tags": [
      "love",
      "relationships",
      "self-worth"
    ],
    "img": "2026-02-03/assets/354f18b7-f814-47ff-8d3e-228124547467.jpeg"
  },
  {
    "slug": "2025-09-07--4yo-Wisdom",
    "path": "2025-09-07/index.md",
    "title": "4yo Wisdom",
    "date": "2025-09-07",
    "tags": [
      "love",
      "family"
    ],
    "img": "2025-09-07/assets/Gemini_Generated_Image_24qpp24qpp24qpp2.png"
  },
  {
    "slug": "2025-07-30--Christian-Ramblings-%232",
    "path": "2025-07-30/index.md",
    "title": "Christian Ramblings #2",
    "date": "2025-07-30",
    "tags": [
      "christianity",
      "faith",
      "scripture",
      "praise"
    ],
    "img": "2025-07-30/assets/6db2dc5c-3543-4aff-98fa-89eb12fa54d4.png"
  },
  {
    "slug": "2025-07-09--Thoughts-on-Praise",
    "path": "2025-07-09/index.md",
    "title": "Thoughts on Praise",
    "date": "2025-07-09",
    "tags": [
      "christianity",
      "faith",
      "praise"
    ],
    "img": "2025-07-09/assets/ChatGPT_Image_Jun_23_2026_06_57_32_PM.png"
  },
  {
    "slug": "2025-07-06--Glimpse",
    "path": "2025-07-06/index.md",
    "title": "Glimpse",
    "date": "2025-07-06",
    "tags": [
      "love",
      "relationships",
      "reflection"
    ],
    "img": "2025-07-06/assets/dbc27496-894e-41e6-aca9-44aa2c7f6d32.png"
  },
  {
    "slug": "2025-04-23--Christian-Ramblings-%231",
    "path": "2025-04-23/index.md",
    "title": "Christian Ramblings #1",
    "date": "2025-04-23",
    "tags": [
      "christianity",
      "faith",
      "scripture",
      "praise",
      "relationships"
    ],
    "img": "2025-04-23/assets/a21cf251-e9a5-4439-afd8-33d2594f83e6.png"
  },
  {
    "slug": "2025-03-17--Conversation-in-the-Womb-%E2%80%93-A-Parable-of-Life-After-Delivery",
    "path": "2025-03-17/index.md",
    "title": "Conversation in the Womb – A Parable of Life After Delivery",
    "date": "2025-03-17",
    "tags": [
      "christianity",
      "faith",
      "parable"
    ],
    "img": "2025-03-17/assets/cover.jpeg"
  },
  {
    "slug": "2025-03-01--Character-of-Love",
    "path": "2025-03-01/index.md",
    "title": "Character of Love",
    "date": "2025-03-01",
    "tags": [
      "love",
      "marriage",
      "relationships"
    ],
    "img": "2025-03-01/assets/cover.jpeg"
  },
  {
    "slug": "2025-01-27--Prune-Your-Time-Like-You-Prune-a-Rose",
    "path": "2025-01-27/index.md",
    "title": "Prune Your Time Like You Prune a Rose",
    "date": "2025-01-27",
    "tags": [
      "productivity",
      "self-improvement"
    ],
    "img": "2025-01-27/assets/cover.jpeg"
  },
  {
    "slug": "2025-01-15--Prayer-Mantra-%232",
    "path": "2025-01-15/index.md",
    "title": "Prayer Mantra #2",
    "date": "2025-01-15",
    "tags": [
      "christianity",
      "faith",
      "relationships"
    ],
    "img": "2025-01-15/assets/rhtFa.jpg"
  },
  {
    "slug": "2024-12-28--2024-Reflection-%E2%80%93-The-Year-of-Openness",
    "path": "2024-12-28/index.md",
    "title": "2024 Reflection – The Year of Openness",
    "date": "2024-12-28",
    "tags": [
      "reflection",
      "life"
    ],
    "img": "2024-12-28/assets/cover.png"
  }
];
