// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.
// Body for: 2026-06-11/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2026-06-11/index.md"] = "# Hello World\n\nJigglypuff\n";
