// Auto-generated by scripts/generate-manifest.mjs — do not edit by hand.
// Body for: 2026-06-11/index.md
(window.ARTICLE_CONTENT = window.ARTICLE_CONTENT || {})["2026-06-11/index.md"] = "# Hello World\n\nJigglypuff\n\n![](articles/2026-06-11/assets/Screenshot_2025-03-01_at_9.43.55_AM.png)\n";
